fcalmaz/core/urls.py
from django.urls import path
from core import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('news/<slug:news_slug>/', views.ShowNews.as_view(), name='news'),
    path('about/', views.AboutClub.as_view(), name='about'),
    path('contact/', views.ContactFormView.as_view(), name='contact')
]

fcalmaz/fcalmaz/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import page_not_found
from fcalmaz import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('team/', include('team.urls', namespace='team')),
    path('events/', include('events.urls', namespace='events')),
    path('users/', include('users.urls', namespace='users')),
    path('forum/', include('forum.urls', namespace='forum')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('captcha/', include('captcha.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = page_not_found


admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Футбольный клуб Алмаз'

fcalmaz/forum/urls.py
from django.urls import path
from forum import views

app_name = 'forum'

urlpatterns = [
    path('home/', views.ForumHome.as_view(), name='forum_home'),
    path('addpost/', views.AddPost.as_view(), name='add_post'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    path('post/<slug:post_slug>/addcomment/', views.AddComment.as_view(), name='add_comment'),
    path('edit/<slug:post_slug>/', views.EditPost.as_view(), name='edit_post'),
    path('delete/<slug:post_slug>/', views.DeletePost.as_view(), name='delete_post'),
    path('comment/<int:comment_id>/edit/', views.EditComment.as_view(), name='edit_comment'),
    path('comment/<int:comment_id>/delete/', views.DeleteComment.as_view(), name='delete_comment'),
]

fcalmaz/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetDoneView, PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView
from users import views
from django.urls import reverse_lazy

app_name = 'users'

urlpatterns = [
    path('login', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name = 'users/password_change_done.html'), name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html', email_template_name = 'users/password_reset_email.html', success_url = reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password-reset/done', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url = reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password-resete/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

fcalmaz/forum/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.contrib.auth import get_user_model

from team.models import translit_to_eng


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_published=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.IntegerChoices):
        DRAFT = 0, 'черновик'
        PUBLISHED = 1, 'опубликованно'
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="Slug")
    photo = models.ImageField(upload_to="post_photo/%y/%m/%d", default=None, blank=True, null=True, verbose_name="Фото")
    content = models.TextField(blank=True, verbose_name="Текст новости", validators=[MinLengthValidator(5, message="Минимум 5 символов"), MaxLengthValidator(10000, message="Максимум 10000 символов")])
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Время изменения")
    is_published = models.BooleanField(choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)), default=Status.DRAFT, verbose_name="Статус")
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='posts', null=True, default=None) 

    objects = models.Manager()
    published = PublishedManager()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('forum:post', kwargs={'post_slug': self.slug})
    
    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        date_slug = slugify(translit_to_eng(str(self.time_create)))
        title_slug = slugify(translit_to_eng(self.title))
        author_slug = slugify(translit_to_eng(self.author.username))

        self.slug = f'{title_slug}-{date_slug}-{author_slug}'
        super().save(*args, **kwargs) 


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост комментария', related_name='comments')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True, default=None) 
    content = models.TextField(blank=True, verbose_name="Текст новости", validators=[MinLengthValidator(5, message="Минимум 5 символов"), MaxLengthValidator(10000, message="Максимум 10000 символов")])                                   
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")

    def __str__(self):
        return f'Комментарий от {self.author.username} к посту "{self.post.title}"'

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

fcalmaz/forum/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Post, Comment


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'photo', 'content', 'is_published']
        widgets = {
            'title': forms.TextInput(),
            'content': forms.Textarea()
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 50:
            raise ValidationError("Длина не должна превышать 50 сиволов.")
        return title
    

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Напишите ваш комментарий...'}),
        }
        labels = {
            'content': '',
        }

fcalmaz/forum/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, CreateView, DetailView, View, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse

from .models import Post, Comment
from .forms import AddPostForm, AddCommentForm
from core.utils import DataMixin
import fcalmaz.settings as settings


class ForumHome(DataMixin, ListView):
    template_name = 'forum/home.html'
    context_object_name = 'posts'
    title_page = 'Главная страница форума'

    def get_queryset(self):
        return Post.published.all().order_by('-time_update')
    

class AddPost(LoginRequiredMixin, CreateView):
    form_class = AddPostForm
    template_name = 'forum/addpost.html'
    title_page = 'Написать пост'

    def form_valid(self, form):
        w = form.save(commit=False)
        w.author = self.request.user
        return super().form_valid(form)
    

class ShowPost(DataMixin, DetailView):
    template_name = 'forum/post.html'
    context_object_name = 'post'
    slug_url_kwarg = 'post_slug'

    def get_object(self, queryset = None):
        return get_object_or_404(Post.objects.all(), slug=self.kwargs[self.slug_url_kwarg])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.all().order_by('time_create')
        context['form_class'] = AddCommentForm()
        context['default_image'] = settings.DEFAULT_USER_IMAGE
        return self.get_mixin_context(context, title=context['post'].title)
    

class AddComment(LoginRequiredMixin, View):
    def post(self, request, post_slug):
        post = get_object_or_404(Post.published, slug=post_slug)
        form = AddCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
        return redirect('forum:post', post_slug=post.slug)


class EditPost(DataMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'photo', 'is_published']
    template_name = 'forum/addpost.html'
    title_page = "Редактирование поста"
    slug_url_kwarg = 'post_slug'
    slug_field = 'slug'

    def get_absolute_url(self):
        return reverse('forum:post', kwargs={'post_slug':self.object.slug})
    

class DeletePost(DataMixin, DeleteView):
    model = Post
    template_name = 'forum/delete_post.html'
    slug_url_kwarg = 'post_slug'
    slug_field = 'slug'

    def get_success_url(self):
        return reverse('forum:forum_home')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context, title = f'Удаление поста: {self.object.title}')
    

class EditComment(DataMixin, UpdateView):
    model = Comment
    form_class = AddCommentForm
    template_name = 'forum/edit_comment.html'
    pk_url_kwarg = 'comment_id'

    def get_success_url(self):
        return reverse('forum:post', kwargs={'post_slug': self.object.post.slug})
    

class DeleteComment(DataMixin, DeleteView):
    model = Comment
    template_name = 'forum/delete_comment.html'
    pk_url_kwarg = 'comment_id'

    def get_success_url(self):
        return reverse('forum:post', kwargs={'post_slug': self.object.post.slug})

fcalmaz/forum/templates/forum/addpost.html
{% extends 'base.html' %}

{% block forum %}
    {% if user.is_authenticated %}
        <li><a href="{% url 'forum:add_post' %}">Написать пост</a></li>
    {% endif %}
{% endblock %}

{% block content %}
<h1>{{title}}</h1>
<form action="" method="post", enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_error }}</div>
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label}}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors}}</div>
    {% endfor %}
    <p>
        <button class="btn-save" type="submit">Сохранить</button>
        {% if form.instance.pk %}  {# Показываем только при редактировании существующего поста #}
            <a href="{% url 'forum:delete_post' post_slug=form.instance.slug %}" class="btn-delete">Удалить пост</a>
        {% endif %}
    </p>
</form>
{% endblock%}

fcalmaz/forum/templates/forum/delete_comment.html
{% extends 'base.html' %}

{% block content %}
<h1>Удаление комментария</h1>
<form method="post">
    {% csrf_token %}
    <p>Вы уверены, что хотите удалить этот комментарий?</p>
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'forum:post' post_slug=object.post.slug %}" class="btn">Отмена</a>
</form>
{% endblock %}

fcalmaz/forum/templates/forum/delete_post.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>
<form method="post">
    {% csrf_token %}
    <p>Вы уверены, что хотите удалить пост "{{ object.title }}"?</p>
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'forum:post' post_slug=object.slug %}" class="btn btn-secondary">Отмена</a>
</form>
{% endblock %}

fcalmaz/forum/templates/forum/edit_comment.html
{% extends 'base.html' %}

{% block content %}
<h1>Редактирование комментария</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn">Сохранить</button>
    <a href="{% url 'forum:post' post_slug=object.post.slug %}" class="btn">Отмена</a>
</form>
{% endblock %}

fcalmaz/forum/templates/forum/home.html
{% extends "base.html" %}
{% load static %}

{% block forum %}
    {% if user.is_authenticated %}
        <li><a href="{% url 'forum:add_post' %}">Написать пост</a></li>
    {% endif %}
{% endblock %}

{% block content %}
<h1 align="center">{{title}}</h1>
    <div class="forum-page">
        <ul class="list-articles">
            {% for p in posts %}
                <li>
                    <div class="article-panel">
                        <p class="first">Автор: {{p.author.username|default:"неизвестен"}}</p>
                        <p class="last">Дата: {{ p.time_update|date:"d-m-y H:i:s" }}</p>
                    </div>

                    {% if p.photo %}
                        <p><img class="img-article-left thumb" src="{{ p.photo.url }}" alt=""></p>
                    {% endif %}

                    <h2>{{ p.title }}</h2>

                    {% autoescape off %}
                        {{ p.content|linebreaks|truncatewords:40 }}
                    {% endautoescape %}

                    <div class="clear"></div>
                    <p class="link-read-post"><a href="{{ p.get_absolute_url }}">Читать пост</a></p>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

{% block navigation %}
    {% if page_obj.has_other_pages %}
        <nav class="list-pages">
            <ul>
                {% if page_obj.has_previous %}
                    <li class="page-num">
                        <a href="?page={{ page_obj.previous_page_number }}"><</a>
                    </li>
                {% endif %}

                {% for p in paginator.page_range %}
                    {% if page_obj.number == p %}
                        <li class="page-num page-num-selected">{{ p }}</li>
                    {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                        <li class="page-num">
                            <a href="?page={{ p }}">{{ p }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-num">
                        <a href="?page={{ page_obj.next_page_number }}">></a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}

fcalmaz/forum/templates/forum/post.html
{% extends 'base.html' %}

{% block forum %}
    {% if user.is_authenticated %}
        <li><a href="{% url 'forum:add_post' %}">Написать пост</a></li>
    {% endif %}
{% endblock %}

{% block content %}
        <div class="post-article">
            <h1>{{ post.title }}</h1>

            <div class="post-meta">
                <p>Автор: <strong>{{ post.author.username }}</strong></p>
                <p>Дата создания: {{ post.time_create|date:"d-m-Y H:i:s" }}</p>
                <p>Последнее изменение: {{ post.time_update|date:"d-m-Y H:i:s" }}</p>
            </div>

            {% if post.photo %}
                <p><img class="news-image" src="{{ post.photo.url }}"></p>
            {% endif %}

            <div class="post-content">
                {{ post.content|linebreaks }}
            </div>

            {% if user.is_authenticated and user == post.author %}
            <div class="edit-post-container">
                <a href="{% url 'forum:edit_post' post.slug %}" class="edit-button">Редактировать пост</a>
            </div>
        {% endif %}
        </div>

        <div class="post-comments">
            <h2>Добавить комментарий</h2>
            {% if user.is_authenticated %}
                <form method="post" action="{% url 'forum:add_comment' post.slug %}">
                    {% csrf_token %}
                    {{ form_class.as_p }}
                    <button type="submit" class="btn">Отправить</button>
                </form>
            {% else %}
                <p>Чтобы оставить комментарий, <a href="{% url 'users:login' %}">войдите</a> или <a href="{% url 'users:register' %}">зарегистрируйтесь</a>.</p>
            {% endif %}

            
            <ul class="comment-list">
                <h3>Комментарии</h3>
                {% for comment in comments %}
                    <li class="comment">
                        <div class="comment-header">
                            {% if comment.author.photo %}
                            <img src="{{ comment.author.photo.url }}" alt="{{ comment.author.username }}" class="avatar" />
                            {% else %}
                            <p><img src="{{ default_image }}" alt="{{ comment.author.username }}" class="avatar"></p>
                            {% endif %}
                            <div class="comment-info">
                                <span class="username">{{ comment.author.username }}</span>
                                <span class="timestamp">{{ comment.time_create|date:"d-m-Y H:i:s" }}</span>
                            </div>
                        </div>
                        <div class="comment-body">
                            <p>{{ comment.content }}</p>
                            {% if user.is_authenticated and user == comment.author %}
                            <div class="comment-actions">
                                <a href="{% url 'forum:edit_comment' comment.id %}" class="btn-save">Редактировать</a>
                                <a href="{% url 'forum:delete_comment' comment.id %}" class="btn-delete">Удалить</a>
                            </div>
                            {% endif %}
                        </div>
                    </li>
                {% empty %}
                    <li>Комментариев пока нет. Будьте первым!</li>
                {% endfor %}
            </ul>
        </div>
{% endblock %}