fcalmaz/core/urls.py
from django.urls import path
from core import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('news/<slug:news_slug>/', views.ShowNews.as_view(), name='news'),
    path('about/', views.AboutClub.as_view(), name='about'),
    path('contact/', views.ContactFormView.as_view(), name='contact')
]

fcalmaz/fcalmaz/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import page_not_found
from fcalmaz import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('team/', include('team.urls', namespace='team')),
    path('events/', include('events.urls', namespace='events')),
    path('users/', include('users.urls', namespace='users')),
    path('forum/', include('forum.urls', namespace='forum')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('captcha/', include('captcha.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = page_not_found


admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Футбольный клуб Алмаз'

fcalmaz/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetDoneView, PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView
from users import views
from django.urls import reverse_lazy

app_name = 'users'

urlpatterns = [
    path('login', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name = 'users/password_change_done.html'), name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html', email_template_name = 'users/password_reset_email.html', success_url = reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password-reset/done', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url = reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password-resete/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

fcalmaz/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
    <link type="text/css" href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="{% static 'core/images/main-ico.png' %}" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <header class="header">
        <nav>
            <ul id="mainmenu" class="mainmenu">
                <li class="logo">
                    <a href="{% url 'home' %}">
                        <div class="logo"></div>
                    </a>
                </li>
                {% for m in menu %}
                    <li><a href="{% url m.url_name %}">{{ m.title }}</a></li>
                {% endfor %}

                {% block forum %}
                {% endblock %}

                {% if user.is_authenticated %}
                    <li class="last">
                        <a href="{% url 'users:profile' %}">{{ user.username }}</a> | 
                        <form id="logoutForm" method="post" action="{% url 'users:logout' %}" style="display: inline;">
                            {% csrf_token %}
                            <a href="#" onclick="document.getElementById('logoutForm').submit(); return false;">Выйти</a>
                        </form>
                    </li>
                {% else %}
                    <li class="last">
                        <a href="{% url 'users:login' %}">Войти</a> | 
                        <a href="{% url 'users:register' %}">Регистрация</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <div class="clear"></div>
    </header>

    <main class="content">
        {% block breadcrumbs %}
        {% endblock %}

        <div class="content-text">
            {% block content %}
            {% endblock %}
        </div>

        {% block navigation %}
        {% endblock %}
    </main>

    <footer class="footer">
        <p>&copy; 2025 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, не запрещается.</p>
    </footer>
</body>
</html>