fcalmaz/core/urls.py
from django.urls import path
from core import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('news/<slug:news_slug>/', views.ShowNews.as_view(), name='news'),
    path('about/', views.AboutClub.as_view(), name='about'),
    path('contact/', views.ContactFormView.as_view(), name='contact')
]

fcalmaz/fcalmaz/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import page_not_found
from fcalmaz import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('team/', include('team.urls', namespace='team')),
    path('events/', include('events.urls', namespace='events')),
    path('users/', include('users.urls', namespace='users')),
    path('forum/', include('forum.urls', namespace='forum')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('captcha/', include('captcha.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = page_not_found


admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Футбольный клуб Алмаз'

fcalmaz/forum/urls.py
from django.urls import path
from forum import views

app_name = 'forum'

urlpatterns = [
    path('home/', views.ForumHome.as_view(), name='forum_home'),
    path('addpost/', views.AddPost.as_view(), name='add_post'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    path('post/<slug:post_slug>/addcomment/', views.AddComment.as_view(), name='add_comment'),
    path('edit/<slug:post_slug>/', views.EditPost.as_view(), name='edit_post'),
    path('delete/<slug:post_slug>/', views.DeletePost.as_view(), name='delete_post'),
    path('comment/<int:comment_id>/edit/', views.EditComment.as_view(), name='edit_comment'),
    path('comment/<int:comment_id>/delete/', views.DeleteComment.as_view(), name='delete_comment'),
]

fcalmaz/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetDoneView, PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView
from users import views
from django.urls import reverse_lazy

app_name = 'users'

urlpatterns = [
    path('login', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name = 'users/password_change_done.html'), name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html', email_template_name = 'users/password_reset_email.html', success_url = reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password-reset/done', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url = reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password-resete/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

fcalmaz/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    photo = models.ImageField(upload_to='user_photo/%Y/%m/%d', blank=True, null=True, verbose_name='Аватар')
    date_birth = models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения')

fcalmaz/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
import datetime


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин/E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email
    

class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, required=False, label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))
    this_year = datetime.date.today().year
    date_birth = forms.DateField(widget=forms.SelectDateWidget(years=tuple(range(this_year-100, this_year-5))))

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email','date_birth', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия'
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'})
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Старый пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label='Новый пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label='Подтверждение пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

fcalmaz/users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.views.generic import CreateView, UpdateView
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm
import fcalmaz.settings as settings
from forum.models import Post


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('users:login')


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {
        'title': 'Профиль пользователя',
        'default_image': settings.DEFAULT_USER_IMAGE,
    }

    def get_success_url(self):
        return reverse_lazy('users:profile')
    
    def get_object(self, queryset = None):
        return self.request.user
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(author=self.request.user)
        return context
    

class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = 'users/password_change_form.html'
    success_url = reverse_lazy('users:password_change_done')

fcalmaz/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Авторизация</h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <div class="form-error">{{ form.non_field_error }}</div>
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label}}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors}}</div>
    {% endfor %}   
    <p><button type="submit">Войти</button></p>

    <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
</form>

<hr>
<p><a href="{% url 'social:begin' 'github' %}"><img src="/media/social-auth/github.jpg"></a></p>
<hr>
<p><a href="{% url 'social:begin' 'google-oauth2' %}"><img src="/media/social-auth/google.png"></a></p>

{% endblock %}

fcalmaz/users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль успешно изменён!</h1>
<p>Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль</a></p>
{% endblock %}

fcalmaz/users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Изменение пароля</h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}"/>
    <div class="form-error">{{ form.non_field_error }}</div>
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label}}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors}}</div>
    {% endfor %}   
    <p><button type="submit">Изменить пароль</button></p>
</form>

{% endblock %}

fcalmaz/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль изменён</h1>

<p>Поздравляем! Пароль успешно изменён, используйте его что бы <a href="{% url 'users:login' %}">войти в систему</a>.</p>
{% endblock %}

fcalmaz/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<h1>Новый пароль</h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <div class="form-error">{{ form.non_field_error }}</div>
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label}}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors}}</div>
    {% endfor %}   
    <p><button type="submit">Сохранить</button></p>

</form>

{% endblock %}

fcalmaz/users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<h1>Сброс пароля</h1>
<p>Инструкция была  отправлена на E-mail</p>
{% endblock %}

fcalmaz/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'In case you’ve forgotten, you are:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

fcalmaz/users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Восстановление пароля</h1>

<form method="post">
    {% csrf_token %}
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label}}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors}}</div>
    {% endfor %}   
    <p><button type="submit">Сбросить по E-mail</button></p>
</form>

{% endblock %}

fcalmaz/users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>Профиль</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% if user.photo %}
    <p><img src="{{ user.photo.url }}"></p>
    {% else %}
    <p><img src="{{ default_image }}"></p>
    {% endif %}
    
    <input type="hidden" name="next" value="{{ next }}"/>
    <div class="form-error">{{ form.non_field_error }}</div>
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label}}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors}}</div>
    {% endfor %}   
    <p><button type="submit">Сохранить</button></p>
</form>

{% if not perms.users.social_auth %}
<hr>
<p><a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
{% endif %}

<hr>
<h2>Мои посты</h2>
{% if posts %}
    <div class="posts-list">
        {% for post in posts %}
            <div class="post-article">
                <div class="post-header">
                    <h3><a href="{% url 'forum:post' post.slug %}">{{ post.title }}</a></h3>
                    <span class="post-status {% if post.is_published %}published{% else %}draft{% endif %}">
                        {% if post.is_published %}Опубликовано{% else %}Черновик{% endif %}
                    </span>
                </div>
                <p>{{ post.content|truncatechars:100 }}</p>
                <div class="post-meta">
                    <time>Дата: {{ post.time_create|date:"d.m.Y H:i" }}</time>
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <div class="post-article">
        <p>Вы пока не опубликовали ни одного поста.</p>
    </div>
{% endif %}



{% endblock %}

fcalmaz/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<h1>Регистрация</h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}"/>
    <div class="form-error">{{ form.non_field_error }}</div>
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label}}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors}}</div>
    {% endfor %}   
    <p><button type="submit">Регистрация</button></p>
    
</form>
{% endblock %}